blueprint:
  name: Trigger light with Namron remote
  description: Toggle lights or switches with a namron remote, or dim lights by holding the button down.
  domain: automation
  input:
    namron_device:
      name: Namron device
      description: The namron switch device to use as a remote.
      selector:
        device:
          integration: zha
          manufacturer: NAMRON AS
    targets:
      name: Button targets
      description: Which light or switch to control for the buttons on the device. The ordering of devices here will correspond with the button ordering on your device.
      selector:
        entity:
          multiple: true
          domain:
            - light
            - switch

mode: single

variables:
  targets: !input targets

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input namron_device
      command: "on"
    id: on_trigger
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input namron_device
      command: "off"
    id: off_trigger
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input namron_device
      command: "move_with_on_off"
    id: dim_trigger

action:
  - if:
      - alias: "No entity for button"
        condition: template
        value_template: |
          {{ (trigger.event.data.endpoint_id | int) > ( targets | length ) }}
    then:
      - stop: "The button number does not have a target."
  - alias: "Set target variable"
    variables:
      target: |
        {{ targets[ trigger.event.data.endpoint_id - 1 ] }}
  - variables:
      target_domain: |
        {{ states[ target ].domain }}
  - choose:
      - conditions:
          - condition: trigger
            id: on_trigger
        sequence:
          - service: |
              {{ target_domain }}.turn_on
            target:
              entity_id: |
                {{ target }}
      - conditions:
          - condition: trigger
            id: off_trigger
        sequence:
          - service: |
              {{ target_domain }}.turn_off
            target:
              entity_id: |
                {{ target }}
      - conditions:
          - condition: trigger
            id: dim_trigger
          - "{{ target_domain == 'light' }}"
        sequence:
          - repeat:
              until: "{{ wait.trigger is not none or repeat.index >= 30 }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: |
                      {{ target }}
                  data_template:
                    brightness_step_pct: |
                      {{ 4 if trigger.event.data.params.move_mode == 0 else -4 }}
                - wait_for_trigger:
                    platform: event
                    event_type: zha_event
                    event_data:
                      device_id: !input namron_device
                      command: "stop_with_on_off"
                      endpoint_id: "{{trigger.event.data.endpoint_id}}"
                  timeout:
                    milliseconds: 150
